=== rti4/undegraduate_samples/Schema/hw6/employee.dtd
<!DOCTYPE payroll [
    <!ELEMENT payroll (employee*)>
	<!ELEMENT employee (name,spouse?,child*,tax-status,ssn,salary,date-of-birth,(manager|staff))>
	<!ELEMENT name (first,middle?,last)>
	<!ELEMENT first (#PCDATA)>
	<!ELEMENT middle (#PCDATA)>
	<!ELEMENT last (#PCDATA)>
	<!ELEMENT spouse (first,middle?,last)>
	<!ELEMENT child (first,middle,last)>
	<!ELEMENT tax-status ((married | single | headOfHousehold | separated))>
	<!ELEMENT ssn (#PCDATA)>
	<!ELEMENT salary (#PCDATA)>
	<!ELEMENT date-of-birth (#PCDATA)>	
	<!ELEMENT manager (#PCDATA)>	
	<!ELEMENT group (#PCDATA)>
	<!ELEMENT yrsAtRank (#PCDATA)>
	<!ELEMENT staff (skill)>
	<!ELEMENT skill (#PCDATA+)>	
]>

=== rti4/undegraduate_samples/Schema/hw6/payroll.xml
<?xml version="1.0"?>
<!DOCTYPE payroll SYSTEM "employee.dtd">
<payroll>
<employee>
  <name>
    <first>Brad</first>
    <middle>T</middle>
    <last>Vander Zanden</last>
  </name>
  <spouse>
      <first>Yifan</first>
      <last>Tang</last>
  </spouse>
  <tax-status>married</tax-status>
  <salary>110000.00</salary>
  <date-of-birth>1964-02-03</date-of-birth>
  <manager title="professor">
    <group>Computer Science</group>
    <yrsAtRank>8</yrsAtRank>
  </manager>
</employee>

<employee>
  <name>
    <first>Don</first>
    <last>Juan</last>
  </name>
  <child>
    <first>Mary</first>
    <middle>H</middle>
    <last>Lamb</last>
  </child>
  <child>
    <first>Fred</first>
    <last>Flintstone</last>
  </child>
  <tax-status>headOfHousehold</tax-status>
  <salary>1553.83</salary>
  <date-of-birth>1980-07-07</date-of-birth>
  <staff>
    <skill>Carpentry</skill>
    <skill>Welding</skill>
    <skill>Plumbing</skill>
  </staff>
</employee>
</payroll>
